CREATE TABLE multiple_choice_question
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question       TEXT                                    NOT NULL,
    correct_answer VARCHAR(255)                            NOT NULL,
    answers        JSONB,
    difficulty     DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_multiple_choice_question PRIMARY KEY (id)
);

CREATE TABLE quick_fire_question
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question   TEXT                                    NOT NULL,
    answer     VARCHAR(255)                            NOT NULL,
    aliases    JSONB,
    difficulty DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_quick_fire_question PRIMARY KEY (id)
);