CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(50)                             NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    surname    VARCHAR(50)                             NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_user_username UNIQUE (username);
